#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'concourse'
require 'bitbar'

client = Concourse::Client.new(
  ENV.fetch('CONCOURSE_URI'),
  username: ENV['CONCOURSE_USER'],
  password: ENV['CONCOURSE_PASSWORD']
)

target_name = ENV.fetch('CONCOURSE_TARGET', 'Concourse')
target = Concourse::Target.new(client)

begin
  pipelines = target.pipelines
rescue StandardError => e
  warn Bitbar::Concourse::ErrorPresenter.new(e, target_name)
  exit 1
end

pipelines = pipelines.select { |pipeline| ARGV.include?(pipeline.name) } if ARGV.any?

latest_builds = pipelines.map do |pipeline|
  pipeline.jobs.map do |job|
    build = job.finished_build
    next unless build

    Bitbar::Concourse::BuildPresenter.new(build)
  end
end.flatten.compact.sort_by(&:end_time).reverse

puts Bitbar::Concourse::AggregatePresenter.new(latest_builds, target_name)
puts '---'
# http://mateoclarke.com/blog/2015/10/14/what-i-learned-boolean-ruby/
latest_builds.group_by(&:'success?').sort_by { |status, _| status ? 1 : 0 }.each do |_, build|
  puts build
  puts '---'
end
